### ISSUE TITLE
Weird bug: Can't use unknown trait 'is' -> 'unmarshalled-by' in an attribute declaration

### ISSUE THREAD

**Issue by CIAvash** [raku-community-modules/JSON-Unmarshal#2]
I was migrating and adding CI to one of my old modules and noticed tests are failing with:
```
Can't use unknown trait 'is' -> 'unmarshalled-by' in an attribute declaration.
```
I knew this module was going to be used instead of tadzik's, but I wasn't expecting this.

I did some investigation and found 2 things that make `is unmarshalled-by` work:
- Using tadzik's JSON::Unmarshal with `use JSON::Unmarshal:ver<0.08>`
- Using this module while adding a `use Test;` in non-test scripts and modules!

**Comment by CIAvash** [comment]
Can I ask for a new release? As this breaks one of my modules, because it uses `JSON::Class` and `JSON::Class` specifies "JSON::Unmarshal:ver<0.08+>" as dependency which causes it to use "JSON::Unmarshal:ver<0.10>" and I can't seem to do anything about it.

/cc @lizmat

**Comment by lizmat** [comment]
Release 0.11 made and uploaded to zef

**Comment by CIAvash** [comment]
Thanks
