### ISSUE TITLE
Recent changes broke META6

### ISSUE THREAD

**Issue by jonathanstowe** [raku-community-modules/JSON-Unmarshal#7]
The commit 96b2d1d200ea815d46806499787ca45a16f0b71f (bisected,) appears to have broken the tests for https://github.com/jonathanstowe/META6 - see https://github.com/jonathanstowe/META6/issues/29

Investigating.

**Comment by jonathanstowe** [comment]
Actually the original reported error is caused by bogus test data that was previously ignored (it does need a fix here to improve the failure mode,)  it basically boils down to having an attribute being defined as positional in a class but being presented a Hash in the JSON, this probably wants to be an explicit exception. 

However fixing that uncovers:

```
not ok 1 - create an object from projects.json
# Failed test 'create an object from projects.json'
# at t/040-projects.t line 24
# Type check failed in assignment to $!depends; expected <anon> but got Mu (Mu.new)
not ok 2 - and they're all META6 objects
# Failed test 'and they're all META6 objects'
# at t/040-projects.t line 25
No such method 'depends' for invocant of type 'Any'
  in block  at t/040-projects.t line 27
  in block <unit> at t/040-projects.t line 16
```

Which basically boils down to it being confused by the anonymous type in:

```
has             $.depends       is rw is specification(Optional) where Positional|Associative;
```

It works fine for the positional case, but the associative gets into a mess in the `multi _unmarshal(%json, Mu $obj is raw)`.  Making another more explicit  `(%, %)` candidate would work but this might not play so nicely with some custom type that implements Associative.

**Comment by vrurg** [comment]
I left a couple of comments to the commit.
